{% set name = "autodocsumm" %}
{% set version = "0.2.11" %}
{% set sha256 = "183212bd9e9f3b58a96bb21b7958ee4e06224107aa45b2fd894b61b83581b9a9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5
    - versioneer
    - tomli
  run:
    - python >=3.5
    - sphinx >=2.2, <=5.0
    - six

test:
  imports:
    - autodocsumm

about:
  home: https://github.com/Chilipp/autodocsumm
  license: Apache-2.0
  license_file: LICENSE
  summary: Extending your autodoc API docs with a summary

  description: |
    This sphinx extension provides some useful extensions to the Sphinxs
    autodoc_ extension. Those include automatic and grouped summary tables for
    modules and classes, as well as documenting the __call__ method
  doc_url: http://autodocsumm.readthedocs.io/
  dev_url: https://github.com/Chilipp/autodocsumm

extra:
  recipe-maintainers:
    - Chilipp
